// flow-typed signature: 5e766c13603688c13b610f024a5a7697
// flow-typed version: <<STUB>>/minireset.css_v^0.0.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minireset.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module "minireset.css" {
  declare module.exports: any;
}
